permissions:
  contents: write

name: amido.stacks.redirect

on:
    pull_request:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Deploy Redirect
        runs-on: ubuntu-latest

        steps:

            # Checkout the documentation repository
            - name: Checkout Repo
              uses: actions/checkout@v2

            # Configure node so that the build can run
            - name: Use NodeJS
              uses: actions/setup-node@v3
              with:
                    node-version: '16.x'

            # Deploy to GHitHub Pages
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.3.3
              with:
                branch: gh-pages
                folder: src
                clean: true